### ISSUE TITLE
Back button in Create Offer dialogue not working as expected when NFT or Token selected.

### ISSUE THREAD

**Issue by andrewhstovell** [xch-dev/sage#152] opened 2024-12-15 09:22 UTC
**Version:**
0.8.1

**Environment:**
Windows 11 Pro 24H2 26100.2605
AMD x64

**Expected:**
- Back button cancels offer creation and returns to previous page (Offers).

**Actual:**
- Works as expected when just XCH is present in maker and/or taker sides.
- However, when NFT or Token are added to either side, back button is unresponsive on first interaction,
second interaction takes user back two steps in their flow.
E.g., if history is Profiles -> Offers -> Create Offer, then the second back click takes user to Profiles page.

**Comment by Rigidity** [comment] 2024-12-18 02:21
Hey @andrewhstovell I just released 0.8.2, are you able to confirm this is still an issue? I can't seem to reproduce it. When I hit the back button it doesn't cancel the offer per se but it does go back to the previous page successfully. I think it's because I made the Make Offer button replace the Offers page in the history, so it doesn't go back to the page that redirected to it.

There's also a Cancel button now which will clear the offer contents.

**Comment by andrewhstovell** [comment] 2024-12-18 03:20
@Rigidity, I can confirm that **issue is now resolved in version 0.8.2**. Further, the addition of the Cancel button works well.
_It's being a little extra of me, but i feel the Cancel/Create buttons may fair better right-aligned on page._

**Comment by Rigidity** [comment] 2024-12-18 04:05
I definitely think the whole page needs a redesign. But for now I'll close this, thanks

**Closed by Rigidity** 2024-12-18 04:05 UTC
Labels: bug, ui
